package cn.didano.base.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.didano.base.model.Bs_acount;
import cn.didano.base.model.Bs_acountExample;

public interface Bs_acountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    long countByExample(Bs_acountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int deleteByExample(Bs_acountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int insert(Bs_acount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int insertSelective(Bs_acount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    List<Bs_acount> selectByExample(Bs_acountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    Bs_acount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bs_acount record, @Param("example") Bs_acountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bs_acount record, @Param("example") Bs_acountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bs_acount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bs_acount record);
}