package cn.didano.base.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.didano.base.model.Bs_catalog;
import cn.didano.base.model.Bs_catalogExample;

public interface Bs_catalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    long countByExample(Bs_catalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int deleteByExample(Bs_catalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int insert(Bs_catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int insertSelective(Bs_catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    List<Bs_catalog> selectByExample(Bs_catalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    Bs_catalog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bs_catalog record, @Param("example") Bs_catalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bs_catalog record, @Param("example") Bs_catalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bs_catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bs_catalog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bs_catalog record);
}