package cn.didano.base.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.didano.base.model.Vd_auth_oss;
import cn.didano.base.model.Vd_auth_ossExample;

public interface Vd_auth_ossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    long countByExample(Vd_auth_ossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int deleteByExample(Vd_auth_ossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int insert(Vd_auth_oss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int insertSelective(Vd_auth_oss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    List<Vd_auth_oss> selectByExample(Vd_auth_ossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    Vd_auth_oss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vd_auth_oss record, @Param("example") Vd_auth_ossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vd_auth_oss record, @Param("example") Vd_auth_ossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Vd_auth_oss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_auth_oss
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vd_auth_oss record);
}