package cn.didano.base.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.didano.base.model.Vd_flow;
import cn.didano.base.model.Vd_flowExample;

public interface Vd_flowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    long countByExample(Vd_flowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int deleteByExample(Vd_flowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int insert(Vd_flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int insertSelective(Vd_flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    List<Vd_flow> selectByExample(Vd_flowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    Vd_flow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vd_flow record, @Param("example") Vd_flowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vd_flow record, @Param("example") Vd_flowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Vd_flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vd_flow record);
}