package cn.didano.base.model;

import java.util.Date;

public class Bs_acount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.user_type
     *
     * @mbg.generated
     */
    private Byte userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.ping_user_id
     *
     * @mbg.generated
     */
    private Integer pingUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.account_balance
     *
     * @mbg.generated
     */
    private Float accountBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.consumption_sum
     *
     * @mbg.generated
     */
    private Float consumptionSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bs_account.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.id
     *
     * @return the value of bs_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.id
     *
     * @param id the value for bs_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.user_id
     *
     * @return the value of bs_account.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.user_id
     *
     * @param userId the value for bs_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.user_type
     *
     * @return the value of bs_account.user_type
     *
     * @mbg.generated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.user_type
     *
     * @param userType the value for bs_account.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.ping_user_id
     *
     * @return the value of bs_account.ping_user_id
     *
     * @mbg.generated
     */
    public Integer getPingUserId() {
        return pingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.ping_user_id
     *
     * @param pingUserId the value for bs_account.ping_user_id
     *
     * @mbg.generated
     */
    public void setPingUserId(Integer pingUserId) {
        this.pingUserId = pingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.created
     *
     * @return the value of bs_account.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.created
     *
     * @param created the value for bs_account.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.account_balance
     *
     * @return the value of bs_account.account_balance
     *
     * @mbg.generated
     */
    public Float getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.account_balance
     *
     * @param accountBalance the value for bs_account.account_balance
     *
     * @mbg.generated
     */
    public void setAccountBalance(Float accountBalance) {
        this.accountBalance = accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.consumption_sum
     *
     * @return the value of bs_account.consumption_sum
     *
     * @mbg.generated
     */
    public Float getConsumptionSum() {
        return consumptionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.consumption_sum
     *
     * @param consumptionSum the value for bs_account.consumption_sum
     *
     * @mbg.generated
     */
    public void setConsumptionSum(Float consumptionSum) {
        this.consumptionSum = consumptionSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.user_name
     *
     * @return the value of bs_account.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.user_name
     *
     * @param userName the value for bs_account.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.phone
     *
     * @return the value of bs_account.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.phone
     *
     * @param phone the value for bs_account.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bs_account.updated
     *
     * @return the value of bs_account.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bs_account.updated
     *
     * @param updated the value for bs_account.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}