package cn.didano.base.model;

import java.util.Date;

public class Vd_auth_object {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.target_id
     *
     * @mbg.generated
     */
    private Integer targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.target_type
     *
     * @mbg.generated
     */
    private Byte targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.owner_id
     *
     * @mbg.generated
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.owner_type
     *
     * @mbg.generated
     */
    private Byte ownerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.auth_type
     *
     * @mbg.generated
     */
    private Byte authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_auth_object.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.id
     *
     * @return the value of vd_auth_object.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.id
     *
     * @param id the value for vd_auth_object.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.target_id
     *
     * @return the value of vd_auth_object.target_id
     *
     * @mbg.generated
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.target_id
     *
     * @param targetId the value for vd_auth_object.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.target_type
     *
     * @return the value of vd_auth_object.target_type
     *
     * @mbg.generated
     */
    public Byte getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.target_type
     *
     * @param targetType the value for vd_auth_object.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(Byte targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.owner_id
     *
     * @return the value of vd_auth_object.owner_id
     *
     * @mbg.generated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.owner_id
     *
     * @param ownerId the value for vd_auth_object.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.owner_type
     *
     * @return the value of vd_auth_object.owner_type
     *
     * @mbg.generated
     */
    public Byte getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.owner_type
     *
     * @param ownerType the value for vd_auth_object.owner_type
     *
     * @mbg.generated
     */
    public void setOwnerType(Byte ownerType) {
        this.ownerType = ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.auth_type
     *
     * @return the value of vd_auth_object.auth_type
     *
     * @mbg.generated
     */
    public Byte getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.auth_type
     *
     * @param authType the value for vd_auth_object.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(Byte authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.created
     *
     * @return the value of vd_auth_object.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.created
     *
     * @param created the value for vd_auth_object.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_auth_object.updated
     *
     * @return the value of vd_auth_object.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_auth_object.updated
     *
     * @param updated the value for vd_auth_object.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}