package cn.didano.base.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Vd_flowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public Vd_flowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdIsNull() {
            addCriterion("vd_channel_id is null");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdIsNotNull() {
            addCriterion("vd_channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdEqualTo(Integer value) {
            addCriterion("vd_channel_id =", value, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdNotEqualTo(Integer value) {
            addCriterion("vd_channel_id <>", value, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdGreaterThan(Integer value) {
            addCriterion("vd_channel_id >", value, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("vd_channel_id >=", value, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdLessThan(Integer value) {
            addCriterion("vd_channel_id <", value, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdLessThanOrEqualTo(Integer value) {
            addCriterion("vd_channel_id <=", value, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdIn(List<Integer> values) {
            addCriterion("vd_channel_id in", values, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdNotIn(List<Integer> values) {
            addCriterion("vd_channel_id not in", values, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdBetween(Integer value1, Integer value2) {
            addCriterion("vd_channel_id between", value1, value2, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andVdChannelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("vd_channel_id not between", value1, value2, "vdChannelId");
            return (Criteria) this;
        }

        public Criteria andDayFlowIsNull() {
            addCriterion("day_flow is null");
            return (Criteria) this;
        }

        public Criteria andDayFlowIsNotNull() {
            addCriterion("day_flow is not null");
            return (Criteria) this;
        }

        public Criteria andDayFlowEqualTo(BigDecimal value) {
            addCriterion("day_flow =", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowNotEqualTo(BigDecimal value) {
            addCriterion("day_flow <>", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowGreaterThan(BigDecimal value) {
            addCriterion("day_flow >", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("day_flow >=", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowLessThan(BigDecimal value) {
            addCriterion("day_flow <", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowLessThanOrEqualTo(BigDecimal value) {
            addCriterion("day_flow <=", value, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowIn(List<BigDecimal> values) {
            addCriterion("day_flow in", values, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowNotIn(List<BigDecimal> values) {
            addCriterion("day_flow not in", values, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("day_flow between", value1, value2, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andDayFlowNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("day_flow not between", value1, value2, "dayFlow");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andSumFlowIsNull() {
            addCriterion("sum_flow is null");
            return (Criteria) this;
        }

        public Criteria andSumFlowIsNotNull() {
            addCriterion("sum_flow is not null");
            return (Criteria) this;
        }

        public Criteria andSumFlowEqualTo(BigDecimal value) {
            addCriterion("sum_flow =", value, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowNotEqualTo(BigDecimal value) {
            addCriterion("sum_flow <>", value, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowGreaterThan(BigDecimal value) {
            addCriterion("sum_flow >", value, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_flow >=", value, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowLessThan(BigDecimal value) {
            addCriterion("sum_flow <", value, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sum_flow <=", value, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowIn(List<BigDecimal> values) {
            addCriterion("sum_flow in", values, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowNotIn(List<BigDecimal> values) {
            addCriterion("sum_flow not in", values, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_flow between", value1, value2, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andSumFlowNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sum_flow not between", value1, value2, "sumFlow");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vd_flow
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vd_flow
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}